global:
  scrape_interval: 15s

  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 5s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"

    scrape_interval: 5s

    static_configs:
      - targets: ["app:8000"]

  - job_name: "redis_exporter"

    scrape_interval: 5s

    static_configs:
      - targets: ["redis_exporter:9121"]

  - job_name: "node-exporter"
    scrape_interval: 15s

    static_configs:
      - targets: ["node-exporter:9100"]
